// ============================================================================
// DIRECTORIO DE CONSULTORAS QA: listado curado de software factories con
// práctica en QA (manual y automation) en Argentina. Sirve de referencia para
// el outreach; NO se scrapea ninguna fuente, son datos verificados a mano.
// Dato estructurado: cada entrada es un objeto con id, nombre y contacto.
// ============================================================================
// Listado curado de consultoras/software factories/staffing con foco o
// práctica de QA (manual & automation) en Argentina. Es un directorio de
// referencia para outreach, no un feed en vivo: no se scrapea ninguna fuente,
// las URLs son las que se verificaron al armar el listado.
export const CONSULTORAS = [
  { id: 'vates', name: 'Vates', category: 'Especializada en QA', city: 'Buenos Aires', note: 'Más de 30 años en testing, QA automation y certificación de software crítico', link: 'https://www.vates.com' },
  { id: 'a1qa', name: 'a1qa (Argentina)', category: 'Especializada en QA', city: 'CABA', note: 'QA para fintech, banca, telecom y gaming', link: 'https://a1qa.ar/' },
  { id: 'qualis-lab', name: 'Qualis Lab', category: 'Especializada en QA', city: 'CABA', note: 'Automation, stress test, mobile testing, UX/vulnerability testing', link: 'https://www.qualis-lab.com/' },
  { id: 'bairesqa', name: 'BairesQA', category: 'Especializada en QA', city: 'Vicente López', note: 'QA de apps web y mobile, alta exposición a terceros', link: 'https://clutch.co/profile/bairesqa' },
  { id: 'gbsys', name: 'GBSYS', category: 'Especializada en QA', city: 'Argentina', note: 'QA y testing: unitarias, integrales, performance', link: 'https://www.gbsys.com/servicios/qa-testing/' },
  { id: 'tester-smart', name: 'Tester Smart', category: 'Especializada en QA', city: 'Puerto Madero, CABA', note: 'Consultoría gerencial y capacitación ISTQB en testing', link: 'https://tester.com.ar/' },
  { id: 'crowdar', name: 'Crowdar', category: 'Especializada en QA', city: 'Buenos Aires', note: 'Consultora de QA/testing + CloudOps; organiza Testear.la. Búsquedas activas: QA/automation/dev/data/cloud/SAP', link: 'https://www.crowdar.com' },
  { id: 'arbusta', name: 'Arbusta', category: 'Especializada en QA', city: 'CABA', note: 'QA manual, empresa con enfoque de inclusión laboral', link: 'https://clutch.co/profile/arbusta' },
  { id: 'nahual-it', name: 'Nahual IT', category: 'Especializada en QA', city: 'Buenos Aires', note: 'Testing con foco también en accesibilidad digital', link: 'https://clutch.co/profile/nahual-it' },
  { id: 'hichex', name: 'hiChex', category: 'Especializada en QA', city: 'Córdoba', note: 'Staffing especializado en recursos de QA', link: 'https://clutch.co/profile/hichex' },
  { id: 'qalified', name: 'QAlified', category: 'Especializada en QA', city: 'Uruguay (con proyectos AR)', note: 'Testing de software, muy bien rankeada', link: 'https://clutch.co/profile/qalified-0' },
  { id: 'betterqa', name: 'BetterQA', category: 'Especializada en QA', city: 'Internacional (atiende AR)', note: 'App testing y QA end-to-end', link: 'https://clutch.co/profile/betterqa' },

  { id: 'baufest', name: 'Baufest', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'QA junto a DevOps y ciberseguridad', link: 'https://developargentina.com/directorio/baufest' },
  { id: 'santex', name: 'Santex', category: 'Consultora IT con área QA', city: 'Córdoba / Buenos Aires', note: 'Desarrollo + QA, +26 años de trayectoria', link: 'https://developargentina.com/directorio/santex' },
  { id: 'snoop-consulting', name: 'Snoop Consulting', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Mobile, QA; clientes como Mercado Libre y Hospital Italiano', link: 'https://developargentina.com/directorio/snoop-consulting' },
  { id: 'grit', name: 'GRIT Tecnología y Soporte', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Infraestructura IT y soporte, incluye QA', link: 'https://developargentina.com/directorio/grit-tecnologia-y-soporte' },
  { id: 'epidata', name: 'Epidata', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Innovation outsourcing, partner de Salesforce/AWS', link: 'https://developargentina.com/directorio/epidata' },
  { id: 'practia', name: 'Practia Argentina', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Práctica dedicada a QA, Testing y Calidad Técnica', link: 'https://argentina.practia.global/servicios/qa-testing-calidad-tecnica/' },
  { id: 'huenei', name: 'Huenei IT Services', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: '+25 años, testing como parte de su portfolio', link: 'https://clutch.co/profile/huenei-it-services' },
  { id: 'xoor', name: 'XOOR Inc.', category: 'Consultora IT con área QA', city: 'Mar del Plata', note: 'Staff augmentation, incluye QA', link: 'https://clutch.co/profile/xoor' },
  { id: 'cumbresoft', name: 'CUMBRESOFT Argentina', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Desarrollo + testing para sector público/educativo', link: 'https://clutch.co/profile/cumbresoft-argentina' },
  { id: 'velocity-partners', name: 'Velocity Partners (Endava)', category: 'Consultora IT con área QA', city: 'Rosario', note: 'QA dentro de su práctica .NET', link: 'https://clutch.co/profile/velocity-partners' },
  { id: 'hexacta', name: 'Hexacta (hoy GlobalLogic)', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Testing e ingeniería de datos', link: 'https://clutch.co/profile/hexacta' },
  { id: 'outside-the-box', name: 'Outside the Box', category: 'Consultora IT con área QA', city: 'Córdoba', note: 'QA + staff augmentation', link: 'https://clutch.co/profile/outside-box-0' },
  { id: 'mobeats', name: 'Mobeats', category: 'Consultora IT con área QA', city: 'Berazategui', note: 'Equipos dedicados a testing en sus proyectos', link: 'https://clutch.co/profile/mobeats' },
  { id: 'neps', name: 'NEPS', category: 'Consultora IT con área QA', city: 'Anisacate, Córdoba', note: 'QA como parte de refactors y desarrollo', link: 'https://clutch.co/profile/neps' },
  { id: 'southern-minds', name: 'Southern Minds', category: 'Consultora IT con área QA', city: 'Rosario', note: 'Testing dentro de sus equipos de producto', link: 'https://clutch.co/profile/southern-minds' },
  { id: 'newbitcrew', name: 'NewBitCrew', category: 'Consultora IT con área QA', city: 'CABA', note: 'Asignan testers dedicados en sus proyectos', link: 'https://clutch.co/profile/newbitcrew' },
  { id: 'kambrica', name: 'Kambrica', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Consultora de producto con testing incluido', link: 'https://clutch.co/profile/kambrica' },
  { id: 'distillery', name: 'Distillery', category: 'Consultora IT con área QA', city: 'Mendoza (HQ California)', note: 'QA testing nearshore, fintech/salud', link: 'https://distillery.co' },
  { id: 'bairesdev', name: 'BairesDev', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Staff augmentation con perfiles QA', link: 'https://clutch.co/profile/bairesdev' },
  { id: 'intive', name: 'intive (ex Hexacta/Belatrix)', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'QA como parte de su oferta de ingeniería', link: 'https://intive.com' },
  { id: 'nanlabs', name: 'NaNLABS', category: 'Consultora IT con área QA', city: 'La Plata', note: 'Boutique técnica, cloud/data con QA', link: 'https://www.nanlabs.com' },

  { id: 'globant', name: 'Globant', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'QA/testing como parte de su ingeniería digital', link: 'https://www.globant.com' },
  { id: 'accenture-ar', name: 'Accenture Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'Incluye Wolox (ex startup argentina adquirida)', link: 'https://www.accenture.com/ar-es' },
  { id: 'ibm-ar', name: 'IBM Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'Consultoría + QA en proyectos grandes', link: 'https://www.ibm.com/ar-es' },
  { id: 'capgemini-ar', name: 'Capgemini Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: '', link: 'https://www.capgemini.com' },
  { id: 'cognizant-ar', name: 'Cognizant Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: '', link: 'https://www.cognizant.com' },
  { id: 'nttdata-ar', name: 'NTT DATA Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: '', link: 'https://www.nttdata.com' },
  { id: 'tcs-ar', name: 'TCS (Tata Consultancy) Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: '', link: 'https://www.tcs.com' },
  { id: 'softtek-ar', name: 'Softtek Argentina', category: 'Multinacional con oficina AR', city: 'La Plata', note: 'Centro Global de Entrega en La Plata', link: 'https://www.softtek.com/es/nuestra-compa%C3%B1ia' },
  { id: 'sonda-ar', name: 'Sonda Argentina', category: 'Multinacional con oficina AR', city: 'CABA', note: '', link: 'https://www.sonda.com' },
  { id: 'endava-ar', name: 'Endava Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'Incluye Velocity Partners (Rosario)', link: 'https://www.endava.com' },
  { id: 'neoris-epam', name: 'Neoris / EPAM Argentina', category: 'Multinacional con oficina AR', city: 'Santa Fe', note: 'Neoris se integró a EPAM en 2024', link: 'https://www.epam.com' },
  { id: 'dxc-ar', name: 'DXC Technology Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: '', link: 'https://www.dxc.com' },

  { id: 'randstad-tech', name: 'Randstad Technologies Argentina', category: 'Staffing / recruiting IT', city: 'CABA', note: 'División IT dedicada, incluye QA', link: 'https://www.randstad.com.ar/empresas/areas-de-expertise/it/' },
  { id: 'adecco-ar', name: 'Grupo Adecco Argentina (IT)', category: 'Staffing / recruiting IT', city: 'Buenos Aires', note: '', link: 'https://www.adecco.com.ar' },
  { id: 'manpower-ar', name: 'ManpowerGroup / Experis Argentina', category: 'Staffing / recruiting IT', city: 'Buenos Aires', note: '', link: 'https://ar.manpowergroup.com' },
  { id: 'sionix', name: 'Sionix', category: 'Staffing / recruiting IT', city: 'Godoy Cruz, Mendoza', note: 'Recruiting técnico especializado', link: 'https://clutch.co/profile/sionix' },
  { id: 'group-assa', name: 'Grupo Assa', category: 'Staffing / recruiting IT', city: 'Buenos Aires', note: 'Consultora de RRHH/IT con selección de perfiles QA', link: 'https://www.grupoassa.com' },
  { id: 'gestal', name: 'Consultora Gestal', category: 'Staffing / recruiting IT', city: 'Córdoba', note: 'Selección/headhunting IT y búsquedas QA remotas (jtrecco@consultoragestal.com)', link: 'https://www.consultoragestal.com' },
  { id: 'contraluz', name: 'Consultora Contraluz', category: 'Staffing / recruiting IT', city: 'CABA', note: 'Búsqueda y selección de personal IT; búsquedas QA en USD (rrhh@consultoracontraluz.com.ar)', link: 'https://www.consultoracontraluz.com.ar' },

  // ---- Ampliación a 100 consultoras ----
  { id: 'lemonit', name: 'LemonIT', category: 'Especializada en QA', city: 'Buenos Aires', note: 'QA y testing como servicio dedicado', link: 'https://clutch.co/profile/lemonit' },
  { id: 'weareleaps', name: 'Leaps', category: 'Consultora IT con área QA', city: 'CABA', note: 'Nearshore IT para USA con práctica QA', link: 'https://clutch.co/profile/leaps' },
  { id: 'binary-studio', name: 'Binary Studio', category: 'Consultora IT con área QA', city: 'Remoto AR', note: 'Dev + QA, modelo remoto con clientes globales', link: 'https://binary-studio.com' },
  { id: 'northbay', name: 'Northbay Solutions', category: 'Consultora IT con área QA', city: 'CABA', note: 'DevOps, cloud y QA', link: 'https://northbay.com' },
  { id: 'better-qa', name: 'Better QA Group', category: 'Especializada en QA', city: 'Buenos Aires', note: 'ContextQA y consultoría en testing', link: 'https://betterqa.co' },
  { id: 'qactions', name: 'QActions', category: 'Especializada en QA', city: 'Buenos Aires', note: 'Boutique de QA/testing, RPA e IA; testing SAP. Vacantes por mail (busquedas@qactions.com)', link: 'https://qactions.com' },
  { id: 'seidor-ar', name: 'Seidor Argentina', category: 'Multinacional con oficina AR', city: 'CABA', note: 'Consultora global de TI con testing', link: 'https://www.seidor.com' },
  { id: 'everis-ntt', name: 'NTT DATA / everis Argentina', category: 'Multinacional con oficina AR', city: 'CABA', note: 'QA dentro de la práctica de transformación digital', link: 'https://www.nttdata.com' },
  { id: 'telecom-ar', name: 'Telecom Argentina (área IT)', category: 'Multinacional con oficina AR', city: 'CABA', note: 'Grandes equipos de QA en productos digitales', link: 'https://www.telecom.com.ar' },
  { id: 'mercadolibre-qa', name: 'Mercado Libre (QA) — Meli', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'Equipos de calidad propios en e-commerce y fintech', link: 'https://www.mercadolibre.com.ar' },
  { id: 'despegar-qa', name: 'Despegar (área QA)', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'QA en viajes y e-commerce', link: 'https://www.despegar.com.ar' },
  { id: 'wolox', name: 'Wolox', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Ex startup AR adquirida por Accenture, QA en sus equipos', link: 'https://clutch.co/profile/wolox' },
  { id: 'knowmad-mood', name: 'Knowmad Mood', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Consultora IT con QA', link: 'https://www.knowmadmood.com' },
  { id: 'sap-labs', name: 'SAP Labs Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'QA dentro del desarrollo de productos SAP', link: 'https://www.sap.com/argentina' },
  { id: 'pwc-ar', name: 'PwC Argentina (Technology)', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'Consultoría tech con QA', link: 'https://www.pwc.com.ar' },
  { id: 'kpmg-ar', name: 'KPMG Argentina (IT Advisory)', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'Proyectos de QA y aseguramiento', link: 'https://kpmg.com/ar' },
  { id: 'deloitte-ar', name: 'Deloitte Argentina (Consulting Tech)', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'SQA en proyectos de transformación', link: 'https://www.deloitte.com/ar-es' },
  { id: 'ey-ar', name: 'EY Argentina (Technology)', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'QA en proyectos de tecnología y datos', link: 'https://www.ey.com/es_ar' },
  { id: 'techint-qa', name: 'Techint (área IT)', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'Equipos IT propios con testing', link: 'https://www.techint.com' },
  { id: 'ypf-qa', name: 'YPF (área Digital)', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'Productos digitales con QA', link: 'https://www.ypf.com' },
  { id: 'devexperts', name: 'Devexperts (área AR)', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Productos financieros con QA', link: 'https://devexperts.com' },
  { id: 'verto', name: 'Vertö', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Desarrollo de software con QA', link: 'https://verto.com.ar' },
  { id: 'factorial-qa', name: 'Factorial HR (QA)', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'Fábrica de HR tech con QA en equipos', link: 'https://factorialhr.com' },
  { id: 'banco-galicia-qa', name: 'Banco Galicia (área IT)', category: 'Banco / Fintech / Billetera', city: 'CABA', note: 'QA en banca digital', link: 'https://www.bancogalicia.com.ar' },
  { id: 'banco-itau-qa', name: 'Itaú Argentina (área Tech)', category: 'Banco / Fintech / Billetera', city: 'CABA', note: 'QA en banca fintech', link: 'https://www.itau.com.ar' },
  { id: 'mereda', name: 'Mereda', category: 'Especializada en QA', city: 'Córdoba', note: 'QA automation para equipos remotos', link: 'https://mereda.dev' },
  { id: 'htqa', name: 'HTQA (Human Team Technology QA)', category: 'Especializada en QA', city: 'Bogotá, Colombia', note: 'Fábrica de pruebas (QA/QC), staffing de QA y aseguramiento. Búsquedas por mail (rrhh@htqasas.com)', link: 'https://www.htqasas.com' },
  { id: 'nttdata-pe', name: 'NTT DATA Perú', category: 'Multinacional con oficina PE', city: 'Lima', note: 'Multinacional global. Vacantes: QA Automatizador Semi Senior / Senior (100% remoto, todas las provincias) CV a gbonillr@nttdata.com', link: 'https://www.nttdata.com' },
  { id: 'soaint-es', name: 'SOAINT (España)', category: 'Consultora IT con área QA', city: 'Madrid, España', note: 'Consultora de tecnología y servicios digitales. Vacante: QA Automation (Madrid, híbrido, jornada completa)', link: 'https://www.soaint.com' },
  { id: 'axonier', name: 'Axonier', category: 'Consultora IT con área QA', city: 'Argentina', note: 'Consultora de TI. Vacante: Analista Funcional +3 años con inglés avanzado (CV a busquedas@axonier.com)', link: 'https://www.axonier.com' },
  { id: 'infotree-pa', name: 'Infotree Service', category: 'Staffing / recruiting IT', city: 'Panamá Pacífico, Panamá', note: 'Staffing IT. Vacante: QA Junior II (híbrido, un año de banca requerido. CV a dvasquez@infotreeservice.com)', link: 'https://www.infotreeservice.com' },
  { id: 'stefanini-ar', name: 'Stefanini Latam', category: 'Staffing / recruiting IT', city: 'Buenos Aires', note: 'Multinacional de TI. Vacante: QA Automation Ssr para cliente bancario (CV a flmarrero@stefanini.com)', link: 'https://stefanini.com' },
  { id: 'universia-ar', name: 'Universia Argentina', category: 'Staffing / recruiting IT', city: 'Buenos Aires', note: 'Red universitaria con portal de empleos. Vacante: Tester/QA automation con foco en agentes inteligentes', link: 'https://www.universia.net' },
  { id: 'rocket-stars', name: 'Rocket Stars', category: 'Staffing / recruiting IT', city: 'Buenos Aires', note: 'Staffing IT. Vacante: QA Automation Engineer SSR (Playwright/Pytest/CI/CD)', link: 'https://rocketstars.com' },
  { id: 'redbee-studios', name: 'redbee Studios', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: '+14 años en industria financiera, remote-first. Vacante: QA Automation SR', link: 'https://redbeestudios.com' },
  { id: 'tsoft-ar', name: 'TSoft Argentina', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Consultora de servicios de TI con área de testing. Vacantes: QA Analyst Senior (arquitecturas distribuidas, AWS, Jira/Xray) y Especialista QA Senior (BDD/TDD, Cypress/Tosca, ISTQB excluyente)', link: 'https://www.tsoftglobal.com' },

  // ---- Bancos y billeteras (equipos de QA propios) ----
  { id: 'banco-nacion', name: 'Banco de la Nación Argentina', category: 'Banco / Fintech / Billetera', city: 'CABA', note: 'Banca pública con equipos de TI y aseguramiento de calidad', link: 'https://www.bna.com.ar' },
  { id: 'banco-provincia', name: 'Banco Provincia', category: 'Banco / Fintech / Billetera', city: 'La Plata', note: 'Banca pública bonaerense, QA en canales digitales', link: 'https://www.bancoprovincia.com.ar' },
  { id: 'banco-ciudad', name: 'Banco Ciudad', category: 'Banco / Fintech / Billetera', city: 'CABA', note: 'Banca pública de la ciudad con banca digital', link: 'https://www.bancociudad.com.ar' },
  { id: 'santander-ar', name: 'Banco Santander Argentina', category: 'Banco / Fintech / Billetera', city: 'CABA', note: 'Banca digital con equipos de QA', link: 'https://www.santander.com.ar' },
  { id: 'bbva-ar', name: 'BBVA Argentina', category: 'Banco / Fintech / Billetera', city: 'CABA', note: 'Transformación digital y testing de banca', link: 'https://www.bbva.com.ar' },
  { id: 'banco-macro', name: 'Banco Macro', category: 'Banco / Fintech / Billetera', city: 'Buenos Aires', note: 'Banca privada con área de sistemas y QA', link: 'https://www.macro.com.ar' },
  { id: 'banco-supervielle', name: 'Banco Supervielle', category: 'Banco / Fintech / Billetera', city: 'CABA', note: 'Banca privada, canales digitales con QA', link: 'https://www.supervielle.com.ar' },
  { id: 'hns', name: 'HSBC Argentina', category: 'Banco / Fintech / Billetera', city: 'CABA', note: 'Banca internacional con testing de sus canales (adquirido por Galicia)', link: 'https://www.hsbc.com.ar' },
  { id: 'banco-cmf', name: 'Banco CMF', category: 'Banco / Fintech / Billetera', city: 'CABA', note: 'Banca de microfinanzas con sistemas propios', link: 'https://www.bancocmf.com.ar' },
  { id: 'galicia-more', name: 'Galicia Más (Más Online)', category: 'Banco / Fintech / Billetera', city: 'CABA', note: 'Plataforma digital del Grupo Galicia', link: 'https://www.bancogalicia.com.ar' },
  { id: 'mercadopago', name: 'Mercado Pago', category: 'Banco / Fintech / Billetera', city: 'Buenos Aires', note: 'Líder fintech de pagos con equipos de QA grandes', link: 'https://www.mercadopago.com.ar' },
  { id: 'uala', name: 'Ualá', category: 'Banco / Fintech / Billetera', city: 'Buenos Aires', note: 'Cuenta + tarjeta, testing payment propio', link: 'https://www.uala.com.ar' },
  { id: 'brubank', name: 'Brubank', category: 'Banco / Fintech / Billetera', city: 'CABA', note: 'Banco 100% digital, QA de app mobile', link: 'https://www.brubank.com' },
  { id: 'naranja-x', name: 'Naranja X', category: 'Banco / Fintech / Billetera', city: 'Córdoba', note: 'Tarjeta y billetera digital, QA en productos', link: 'https://www.naranjax.com' },
  { id: 'modo', name: 'MODO (Billetera)', category: 'Banco / Fintech / Billetera', city: 'CABA', note: 'Billetera interoperable de bancos, testing payment', link: 'https://www.modo.com.ar' },
  { id: 'personal-pay', name: 'Personal Pay', category: 'Banco / Fintech / Billetera', city: 'CABA', note: 'Billetera de Telecom Argentina', link: 'https://www.personal.com.ar/pay' },
  { id: 'lemon-cash', name: 'Lemon Cash', category: 'Banco / Fintech / Billetera', city: 'Buenos Aires', note: 'Fintech cripto con wallet, QA de productos', link: 'https://lemon.me' },
  { id: 'belo', name: 'Belo', category: 'Banco / Fintech / Billetera', city: 'Buenos Aires', note: 'Wallet cripto, equipo tech con QA', link: 'https://www.belo.app' },
  { id: 'cocos', name: 'Cocos Capital', category: 'Banco / Fintech / Billetera', city: 'Buenos Aires', note: 'Plataforma de inversión/cripto (Grupo Cocos; integra Banco Voii). Vacantes: senior-qa-engineer', link: 'https://cocos.capital' },
  { id: 'astro-pay', name: 'AstroPay', category: 'Banco / Fintech / Billetera', city: 'Buenos Aires', note: 'Medios de pago globales, QA fintech', link: 'https://www.astropay.com' },
  { id: 'buenbit', name: 'Buenbit', category: 'Banco / Fintech / Billetera', city: 'Buenos Aires', note: 'Exchange y wallet cripto', link: 'https://www.buenbit.com' },
  { id: 'ripio', name: 'Ripio', category: 'Banco / Fintech / Billetera', city: 'Buenos Aires', note: 'Fintech cripto con app y QA', link: 'https://www.ripio.com' },
  { id: 'paypal-ar', name: 'PayPal (área AR)', category: 'Banco / Fintech / Billetera', city: 'Buenos Aires', note: 'Presencia en Argentina con equipos tech', link: 'https://www.paypal.com' },
  { id: 'payoneer-ar', name: 'Payoneer (área AR)', category: 'Banco / Fintech / Billetera', city: 'Buenos Aires', note: 'Pagos internacionales, QA en plataforma', link: 'https://www.payoneer.com' },
  { id: 'dolarap', name: 'DolarApp', category: 'Banco / Fintech / Billetera', city: 'Buenos Aires', note: 'Cuenta en dólares digital, fintech', link: 'https://www.dolarapp.com' },

  // ---- Gobierno / Sector público (organismos que requieren QA) ----
  { id: 'gob-innovacion', name: 'Secretaría de Innovación y Transformación Digital', category: 'Gobierno / Sector Público', city: 'CABA', note: 'Proyectos de gobierno digital y calidad de software', link: 'https://www.argentina.gob.ar' },
  { id: 'sec-pressupuesto', name: 'Secretaría de Presupuesto y Hacienda', category: 'Gobierno / Sector Público', city: 'CABA', note: 'Sistemas de gestión presupuestaria con QA', link: 'https://www.argentina.gob.ar' },
  { id: 'anses', name: 'ANSES', category: 'Gobierno / Sector Público', city: 'CABA', note: 'Desarrollo propio de sistemas con aseguramiento de calidad', link: 'https://www.anses.gob.ar' },
  { id: 'afip', name: 'AFIP', category: 'Gobierno / Sector Público', city: 'CABA', note: 'Grandes plataformas tributarias con áreas de testing', link: 'https://www.afip.gob.ar' },
  { id: 'rentas-ba', name: 'ARBA (Agencia de Recaudación Bs. As.)', category: 'Gobierno / Sector Público', city: 'La Plata', note: 'Sistemas de recaudación con QA', link: 'https://www.arba.gov.ar' },
  { id: 'dgi-mza', name: 'ATR Mendoza (recaudación)', category: 'Gobierno / Sector Público', city: 'Mendoza', note: 'Recaudación provincial, sistemas con testing', link: 'https://atm.mendoza.gov.ar' },
  { id: 'renaper', name: 'Renaper', category: 'Gobierno / Sector Público', city: 'CABA', note: 'Identidad digital y biometría, QA de seguridad', link: 'https://www.argentina.gob.ar/interior/renaper' },
  { id: 'gcba', name: 'Gobierno de la Ciudad de Buenos Aires', category: 'Gobierno / Sector Público', city: 'CABA', note: 'Servicios digitales ciudadanos con equipos de QA', link: 'https://buenosaires.gob.ar' },
  { id: 'gba-sistemas', name: 'Sistemas del Gobierno de la Provincia de Bs. As.', category: 'Gobierno / Sector Público', city: 'La Plata', note: 'Aplicaciones provinciales con aseguramiento de calidad', link: 'https://www.gba.gob.ar' },
  { id: 'intia', name: 'INTA', category: 'Gobierno / Sector Público', city: 'CABA', note: 'Instituto Nacional de Tecnología Agropecuaria, sistemas con QA', link: 'https://www.argentina.gob.ar/inta' },
  { id: 'conicet', name: 'CONICET (área sistemas)', category: 'Gobierno / Sector Público', city: 'CABA', note: 'Sistemas de gestión científica con QA', link: 'https://www.conicet.gov.ar' },
  { id: 'enacom', name: 'ENACOM', category: 'Gobierno / Sector Público', city: 'CABA', note: 'Organismo regulador con sistemas y testing', link: 'https://www.enacom.gob.ar' },
  { id: 'pami', name: 'PAMI', category: 'Gobierno / Sector Público', city: 'CABA', note: 'Sistemas de obra social con aseguramiento de calidad', link: 'https://www.pami.org.ar' },
  { id: 'andas', name: 'Andas (Sistemas de Obra Social)', category: 'Gobierno / Sector Público', city: 'CABA', note: 'Sistemas de salud y prestaciones con QA', link: 'https://www.andas.org.ar' },
  { id: 'undav-sistemas', name: 'Sistemas UNLP / Universidades Nacionales', category: 'Gobierno / Sector Público', city: 'La Plata', note: 'Sistemas universitarios y de gestión académica', link: 'https://www.unlp.edu.ar' },
  { id: 'aduba', name: 'ADUBA (Aduana)', category: 'Gobierno / Sector Público', city: 'CABA', note: 'Sistema aduanero con áreas de calidad', link: 'https://www.argentina.gob.ar/aduana' },
  { id: 'poder-judicial', name: 'Poder Judicial de la Nación', category: 'Gobierno / Sector Público', city: 'CABA', note: 'Sistemas judiciales (lex/pje) con QA', link: 'https://www.pjn.gov.ar' },
  { id: 'moral-chubut', name: 'Sistemas Provincia de Chubut', category: 'Gobierno / Sector Público', city: 'Rawson', note: 'Gobierno digital provincial', link: 'https://www.chubut.gov.ar' },
  { id: 'ecosistema-cordoba', name: 'Gobierno de Córdoba (TICs)', category: 'Gobierno / Sector Público', city: 'Córdoba', note: 'Gobierno digital provincial con QA', link: 'https://www.cba.gov.ar' },
  { id: 'gsm-santa_fe', name: 'Gobierno de Santa Fe (TICs)', category: 'Gobierno / Sector Público', city: 'Santa Fe', note: 'Servicios digitales provinciales', link: 'https://www.santafe.gob.ar' },
];
