// ============================================================================
// OFERTAS CURADAS A MANO por Ali: relevadas directamente de las bolsas propias
// de cada consultora (mail, portal propio, LinkedIn). Complementan a las
// fuentes en vivo y el motor de matching les calcula el % como al resto.
// Dato estructurado y ordenado por región.
// ============================================================================
// Ofertas relevadas a mano (bolsas propias de cada consultora: mail, portal
// propio, LinkedIn). No salen de las fuentes remotas escaneadas; se agregan
// manualmente a su país (región). Cada entrada incluye el texto de la vacante
// con sus skills para que el motor de matching calcule el % correctamente.
export const CURATED_JOBS = [
  // ============ ARGENTINA ============
  {
    id: 'curated-crowdar-qa',
    source: 'Directo (Crowdar)',
    title: 'QA / QA Automation Engineer',
    company: 'Crowdar',
    location: 'Buenos Aires, Argentina',
    regionGuess: 'argentina',
    applyUrl: 'https://crowdar.peopleforce.io/careers',
    description:
      'Crowdar (organizadora de Testear.la) suma perfiles de QA y Testing: QA Automation, Tester Manual, Chapter Lead, y roles en automatización, desarrollo, data, cloud y SAP. Valoramos experiencia en testing funcional y automatizado (web y mobile), APIs, y conocimiento de metodologías ágiles. Suma el uso de IA aplicada a testing y automatización inteligente.',
    tags: ['qa', 'qa automation', 'testing', 'automation', 'manual testing', 'api testing'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-qactions-sap',
    source: 'Directo (QActions)',
    title: 'QA Manager / Test Manager SAP',
    company: 'QActions',
    location: 'Buenos Aires, Argentina',
    regionGuess: 'argentina',
    applyUrl: 'https://qactions.com',
    description:
      'En QActions buscamos un perfil con experiencia comprobable en testing de implementaciones o upgrades SAP, para liderar estrategias, equipos y planes de prueba hasta el go-live. Valoramos experiencia como QA Lead, Test Lead SAP, Testing Manager o Líder de Testing y contacto con clientes. Excluyente Buenos Aires, modalidad híbrida. Postulación por mail a busquedas@qactions.com.',
    tags: ['qa', 'testing', 'sap', 'test lead', 'test manager', 'agile'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-cocos-qa',
    source: 'Directo (Cocos Capital)',
    title: 'Senior QA Engineer',
    company: 'Cocos Capital',
    location: 'Buenos Aires, Argentina',
    regionGuess: 'argentina',
    applyUrl: 'https://cocoscapital.recruitee.com/o/senior-qa-engineer',
    description:
      'Cocos Capital, fintech argentina de inversión y cripto, busca Senior QA Engineer (híbrido, Buenos Aires). Buscamos experiencia en productos digitales, idealmente fintech, banca, pagos o cripto. Suma contar con background en desarrollo de software, usar herramientas de IA aplicadas a testing (GitHub Copilot, agentic QA tools, generación de test cases con LLMs) y experiencia en testing de seguridad.',
    tags: ['qa', 'senior qa', 'testing', 'fintech', 'automation', 'api testing'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-ar-fx-analista-funcional',
    source: 'Directo (FX Informática)',
    title: 'Analista Funcional',
    company: 'FX Informática',
    location: 'Argentina (Remoto)',
    regionGuess: 'argentina',
    applyUrl: 'https://www.fxinformatica.com',
    description:
      'FX Informática busca Analistas Funcionales para proyectos internos y externos: relevamiento de requerimientos, testing, soporte y capacitación a usuarios, documentación y demostraciones de productos. Orientado a estudiantes o graduados de Administración, Comercio Internacional, Sistemas o afines. Valoramos capacidad de análisis, trabajo en equipo, comunicación, gestión de proyectos, manejo de Jira y SQL, inglés y/o portugués. Remoto lunes a viernes 9-18hs. Enviar CV a rrhh@fxinformatica.com.',
    tags: ['qa', 'analista funcional', 'analista', 'testing', 'jira', 'sql', 'functional testing'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-ar-fx-desarrollador',
    source: 'Directo (FX Informática)',
    title: 'Desarrollador (células de desarrollo)',
    company: 'FX Informática',
    location: 'Argentina (Remoto)',
    regionGuess: 'argentina',
    applyUrl: 'https://www.fxinformatica.com',
    description:
      'FX Informática busca desarrolladores para células de desarrollo: diseño, desarrollo, configuración y entrega de soluciones de software. Conocimientos en .NET Core / C#, SQL Server, HTML5, CSS y JavaScript. Se valoran Git/TFS, DevOps, Azure, Oracle y metodologías ágiles. Remoto lunes a viernes 9-18hs. Enviar CV a rrhh@fxinformatica.com.',
    tags: ['quality', 'test', 'javascript', 'sql', 'agile', 'azure devops', 'ci/cd'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-ar-aliantum-tester-focal',
    source: 'Directo (Aliantum)',
    title: 'Tester Focal Point (QA / Testing Lead Operativo)',
    company: 'Aliantum',
    location: 'CABA, Argentina',
    regionGuess: 'argentina',
    applyUrl: 'https://www.aliantum.com.ar/jobs/tester-focal-point-8',
    description:
      'Aliantum (consultora IA First especializada en el sector financiero LATAM) busca Focal Point de Testing: referente central de testing como nexo entre el cliente, el equipo de desarrollo y stakeholders. Ordena, prioriza, da visibilidad y toma decisiones operativas de QA. Responsabilidades: definir la estrategia de testing (funcional, regresión, smoke, UAT), analizar requerimientos, diseñar y supervisar casos de prueba, coordinar backlog de bugs, validar go / no go a producción, trazabilidad requerimiento → caso de prueba → defecto y acompañar UAT. Requisitos: experiencia como Tester/QA, manejo de Jira, Azure DevOps, TestRail o similares, conocimiento de Core Banking BANTOTAL, y disponibilidad para viajar y estar presencial en el cliente (excluyente). Deseable: entornos bancarios/fintech, SQL, APIs, metodologías ágiles (Scrum/Kanban) y experiencia como referente o lead informal de testing.',
    tags: ['qa', 'tester', 'test lead', 'testing', 'functional testing', 'regression', 'uat', 'bantotal', 'core banking', 'jira', 'azure devops', 'testrail', 'agile', 'scrum', 'kanban'],
    salary: '',
    date: '2026-09-08',
  },
  {
    id: 'curated-ar-decampoacampo-qa-auto',
    source: 'Directo (deCampoaCampo)',
    title: 'QA Automation Ssr/Senior (Cypress)',
    company: 'deCampoaCampo',
    location: 'CABA/GBA (1 día presencial) o 100% remoto (interior)',
    regionGuess: 'argentina',
    applyUrl: 'https://lnkd.in/djFuZr5d',
    description:
      'deCampoaCampo (mercado ganadero digital más grande de Argentina, agtech) busca QA Automation Ssr/Senior con experiencia en Cypress y JavaScript. Esquema: CABA/GBA con 1 día presencial en la oficina de CABA, o 100% remoto para candidatos del interior del país. Postulación a través del link del anuncio o por mail a rrhh@decampoacampo.com. Otras búsquedas en su portal de empleos.',
    tags: ['qa automation', 'automation', 'cypress', 'javascript', 'testing', 'regression', 'agile'],
    salary: '',
    date: '2026-09-08',
  },
  {
    id: 'curated-ar-gestal-tester-sr',
    source: 'Directo (Consultora Gestal)',
    title: 'Tester Senior / QA Automation',
    company: 'Consultora Gestal (bolsa de empleo)',
    location: 'Argentina (100% Remoto)',
    regionGuess: 'argentina',
    applyUrl: 'https://www.consultoragestal.com/bolsa-de-trabajo/',
    description:
      'Búsqueda activa de Consultora Gestal: Tester Senior / QA Automation 100% remoto, full time lunes a viernes, modalidad monotributo en Argentina. Requisitos: automatización de pruebas de Frontend y APIs, conocimientos de SQL y de programación, y uso de herramientas de IA aplicadas al testing. No piden experiencia en una herramienta de testing específica: priorizan base técnica y capacidad de adaptación. Ofrecen 100% remoto, prepaga, vacaciones pagas y crecimiento. Postulación por mail a jtrecco@consultoragestal.com.',
    tags: ['qa', 'qa automation', 'automation', 'api testing', 'frontend testing', 'sql', 'testing', 'ai', 'ia'],
    salary: '',
    date: '2026-09-08',
  },
  {
    id: 'curated-ar-contraluz-qa-ai-agents',
    source: 'Directo (Consultora Contraluz)',
    title: 'QA Automation Engineer – AI & Agentic Systems',
    company: 'Consultora Contraluz',
    location: 'Argentina (100% Remoto)',
    regionGuess: 'argentina',
    applyUrl: 'https://www.consultoracontraluz.com.ar',
    description:
      'Búsqueda de Consultora Contraluz para un cliente: QA Automation Engineer especializado en AI & Agentic Systems, 100% remoto desde Argentina, modalidad contractor con remuneración en dólares (3k USD). Inglés conversacional fluido excluyente. Requisitos: 2+ años como QA Automation/Test Automation, experiencia comprobable en testing de Agentes de IA y/o sistemas basados en LLM, programación en Python y/o TypeScript, automatización de navegador (Playwright, Selenium, Puppeteer), API testing, suites automatizadas, debugging, CI/CD (GitHub Actions, Jenkins, GitLab CI), análisis de logs/trazas/llamadas de red y métricas de calidad (Grafana, Kibana, Power BI). Trabajo con resultados variables o no determinísticos. Enviar CV a rrhh@consultoracontraluz.com.ar con asunto "QA Automation Engineer AI & Agentic Systems".',
    tags: ['qa automation', 'automation', 'ai', 'ia', 'llm', 'agents', 'agentic', 'python', 'typescript', 'playwright', 'selenium', 'puppeteer', 'api testing', 'ci/cd', 'github actions', 'jenkins', 'gitlab ci', 'grafana', 'kibana'],
    salary: '3k USD',
    date: '2026-09-08',
  },
  {
    id: 'curated-ar-nttdata-qa-automatizador',
    source: 'Reclutador (LinkedIn)',
    title: 'QA Automatizador (NTT DATA)',
    company: 'NTT DATA',
    location: 'Argentina',
    regionGuess: 'argentina',
    applyUrl: '',
    description:
      'NTT DATA busca perfiles de QA Automatizador para un nuevo proyecto. Requisitos: egresado/a de carrera técnica o universitaria en Sistemas/Informática o afines; experiencia en automatización de pruebas; experiencia con Karate para automatización de APIs; Java y/o Python; Selenium, Cucumber, Appium y/o Gherkin; Git, Postman, REST Assured, Jira y Confluence; metodologías ágiles. ISTQB Foundation es un plus. Importante: buscan personas que no hayan trabajado anteriormente en NTT DATA. Postulación por DM con el reclutador (publicación #Hiring #QAAutomation #Testing).',
    tags: ['qa automation', 'automation', 'karate', 'api testing', 'java', 'python', 'selenium', 'cucumber', 'appium', 'gherkin', 'test automation', 'istqb', 'jira', 'agile'],
    salary: '',
    date: '2026-09-08',
  },
  {
    id: 'curated-ar-qa-sr-js-webdriverio',
    source: 'Reclutador (LinkedIn)',
    title: 'Sr. QA Automation Engineer (JavaScript)',
    company: 'Confidencial (AR/CO/MX/BR)',
    location: 'Argentina (100% Remoto)',
    regionGuess: 'argentina',
    applyUrl: '',
    description:
      'Sr. QA Automation Engineer (JavaScript) para un proyecto global en crecimiento, 100% remoto (AR/CO/MX/BR). Requisitos: +5 años en Quality Testing, +3 años en QA Automation, pipelines CI/CD (CircleCI preferido), automatización frontend con JavaScript + WebdriverIO, automatización backend, diseño orientado a objetos y bases de datos relacionales y no relacionales. Qué vas a hacer: liderar la calidad end-to-end, diseñar y mantener suites de automatización frontend/backend, coordinar releases completos (go/no-go, sanity checks post-deploy), visibilidad de cobertura/riesgos, proponer mejoras y roadmap de calidad. Postulación por MD (publicación #QA #Automation #SDET #JavaScript #WebdriverIO).',
    tags: ['qa automation', 'automation', 'sdet', 'javascript', 'webdriverio', 'ci/cd', 'circleci', 'frontend testing', 'api testing', 'backend testing', 'release management'],
    salary: '',
    date: '2026-09-08',
  },
  {
    id: 'curated-ar-link-automation-tester',
    source: 'Directo (link)',
    title: 'Automation Tester Sr (POS - Backend)',
    company: 'link',
    location: 'Buenos Aires (Híbrido, zona Luna Park)',
    regionGuess: 'argentina',
    applyUrl: 'https://lnkd.in/dpVqvFhm',
    description:
      'link (Red Link S.A., ecosistema financiero/pagos) busca Automation Tester POS - Backend para el equipo de Procesamiento Adquirente. Objetivo: generar, ejecutar y automatizar planes de prueba (código evolutivo y regresión) garantizando calidad, estabilidad y seguridad en la integración de medios de pago. Requisitos: graduado/a, promediando o finalizando Ingeniería en Sistemas o afines; 3 a 5+ años en posiciones similares en medios de pago y/o servicios financieros; programación y automatización de pruebas; API REST y modelado de bases de datos; documentación técnico-funcional. Deseable: sistemas de cobro sobre dispositivos POS y PinPad, flujos de pagos adquirentes, normativas (PCI, Banco Central, EMVCo) y certificaciones (Integración, L3, PCI). Ofrecen híbrido, bono anual, revisiones salariales y medicina prepaga. Postular en el link.',
    tags: ['qa automation', 'automation', 'api testing', 'rest', 'pos', 'pinpad', 'payments', 'medios de pago', 'adquirencia', 'backend testing', 'emvco', 'pci', 'banca'],
    salary: '',
    date: '2026-09-08',
  },

  // ============ MÉXICO ============
  {
    id: 'curated-mx-coderdoad-qa-auto',
    source: 'Tech Jobs in Mexico',
    title: 'QA Automation Engineer',
    company: 'CodeRoad Inc',
    location: 'México (100% Remoto)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/ez9E4ydp',
    description:
      'Búsqueda en Tech Jobs in Mexico: QA Automation Engineer en CodeRoad Inc, modalidad 100% remota para todo el país. Automatización de pruebas, testing funcional y de regresión, APIs y metodologías ágiles.',
    tags: ['qa automation', 'automation', 'testing', 'api testing', 'agile'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-coderdoad-qa-manual',
    source: 'Tech Jobs in Mexico',
    title: 'Sr. QA Manual Engineer',
    company: 'CodeRoad Inc',
    location: 'México (100% Remoto)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/e6TzVEJ7',
    description:
      'Búsqueda en Tech Jobs in Mexico: Sr. QA Manual Engineer en CodeRoad Inc, modalidad 100% remota. Pruebas funcionales, manuales y de regresión con foco en calidad de software.',
    tags: ['qa', 'manual testing', 'testing', 'functional testing', 'regression'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-rapptr-qa-analyst',
    source: 'Tech Jobs in Mexico',
    title: 'QA Analyst',
    company: 'Rapptr Labs',
    location: 'México (100% Remoto)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/da-MPwxD',
    description:
      'Búsqueda en Tech Jobs in Mexico: QA Analyst en Rapptr Labs, modalidad 100% remota. Análisis y ejecución de pruebas funcionales, test cases y reporte de defectos en entornos ágiles.',
    tags: ['qa', 'testing', 'functional testing', 'test cases', 'agile'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-devlane-sr-qa',
    source: 'Tech Jobs in Mexico',
    title: 'Sr. QA Engineer',
    company: 'Devlane',
    location: 'México (100% Remoto)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/eK27UxgU',
    description:
      'Búsqueda en Tech Jobs in Mexico: Sr. QA Engineer en Devlane, modalidad 100% remota. Liderar estrategias de testing manual y automatizado, APIs, web y mobile en equipos ágiles.',
    tags: ['qa', 'senior qa', 'testing', 'automation', 'api testing', 'mobile testing'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-gila-sdet',
    source: 'Tech Jobs in Mexico',
    title: 'QA/SDET Engineer',
    company: 'Gila Software',
    location: 'México (100% Remoto)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/ebSZhGAt',
    description:
      'Búsqueda en Tech Jobs in Mexico: QA/SDET Engineer en Gila Software, modalidad 100% remota. Automatización de pruebas, diseño de frameworks de testing, APIs y CI/CD.',
    tags: ['qa', 'sdet', 'automation', 'test automation', 'api testing', 'ci/cd'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-nexaminds-qa-auto',
    source: 'Tech Jobs in Mexico',
    title: 'QA Automation Engineer',
    company: 'Nexaminds',
    location: 'México (100% Remoto)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/e_qX8HQY',
    description:
      'Búsqueda en Tech Jobs in Mexico: QA Automation Engineer en Nexaminds, modalidad 100% remota. Automatización de pruebas web, mobile y APIs con foco en calidad.',
    tags: ['qa automation', 'automation', 'testing', 'mobile testing', 'api testing'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-globallogic-sr-auto',
    source: 'Tech Jobs in Mexico',
    title: 'Sr. Automation QA Engineer',
    company: 'GlobalLogic',
    location: 'CDMX, México (Híbrido)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/e22H2wyh',
    description:
      'Búsqueda en Tech Jobs in Mexico: Sr. Automation QA Engineer en GlobalLogic, modalidad híbrida en CDMX. Automatización de pruebas a gran escala, frameworks de testing, APIs y entornos ágiles.',
    tags: ['qa automation', 'automation', 'testing', 'api testing', 'agile'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-felix-sr-qa-auto',
    source: 'Tech Jobs in Mexico',
    title: 'Senior QA Automation Engineer',
    company: 'Félix',
    location: 'CDMX, México (Híbrido)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/gAeHh_Q6',
    description:
      'Búsqueda en Tech Jobs in Mexico: Senior QA Automation Engineer en Félix, modalidad híbrida en CDMX. Fintech de pagos; automatización de pruebas, APIs y servicios financieros.',
    tags: ['qa automation', 'automation', 'testing', 'api testing', 'fintech'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-verifone-qa-analyst',
    source: 'Tech Jobs in Mexico',
    title: 'Software QA Analyst',
    company: 'Verifone',
    location: 'CDMX, México (Híbrido)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/euZN3p8H',
    description:
      'Búsqueda en Tech Jobs in Mexico: Software QA Analyst en Verifone, modalidad híbrida en CDMX. Análisis y ejecución de pruebas funcionales y de regresión en productos de tecnología de pagos.',
    tags: ['qa', 'testing', 'functional testing', 'regression'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-mtech-qa-tester',
    source: 'Tech Jobs in Mexico',
    title: 'QA Tester',
    company: 'MTech Systems',
    location: 'Querétaro, México (Híbrido)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/eBwRQ_U7',
    description:
      'Búsqueda en Tech Jobs in Mexico: QA Tester en MTech Systems, modalidad híbrida en Querétaro. Ejecución de pruebas manuales y funcionales, test cases y reporte de defectos.',
    tags: ['qa', 'tester', 'manual testing', 'functional testing', 'test cases'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-qa-sr-js-webdriverio',
    source: 'Reclutador (LinkedIn)',
    title: 'Sr. QA Automation Engineer (JavaScript)',
    company: 'Confidencial (AR/CO/MX/BR)',
    location: 'México (100% Remoto)',
    regionGuess: 'mexico',
    applyUrl: '',
    description:
      'Sr. QA Automation Engineer (JavaScript) para un proyecto global en crecimiento, 100% remoto (AR/CO/MX/BR). Requisitos: +5 años en Quality Testing, +3 años en QA Automation, pipelines CI/CD (CircleCI preferido), automatización frontend con JavaScript + WebdriverIO, automatización backend, diseño orientado a objetos y bases de datos relacionales y no relacionales. Qué vas a hacer: liderar la calidad end-to-end, diseñar y mantener suites de automatización frontend/backend, coordinar releases completos (go/no-go, sanity checks post-deploy), visibilidad de cobertura/riesgos, proponer mejoras y roadmap de calidad. Postulación por MD (publicación #QA #Automation #SDET #JavaScript #WebdriverIO).',
    tags: ['qa automation', 'automation', 'sdet', 'javascript', 'webdriverio', 'ci/cd', 'circleci', 'frontend testing', 'api testing', 'backend testing', 'release management'],
    salary: '',
    date: '2026-09-08',
  },
  {
    id: 'curated-mx-qa-mid-manual-technical',
    source: 'Reclutador (LinkedIn)',
    title: 'Quality Assurance Engineer Mid (Manual + Técnico)',
    company: 'Confidencial (México)',
    location: 'México (100% Remoto)',
    regionGuess: 'mexico',
    applyUrl: '',
    description:
      'Quality Assurance Engineer Mid para equipo de ingeniería con foco en QA manual y profundidad técnica (no es QA manual tradicional ni Automation Engineer puro). Mayor parte del trabajo: functional y regression testing, validación de funcionalidades, seguimiento de bugs y exploración de escenarios. También: APIs REST con Postman, Git, Linux/Unix y línea de comandos, revisión de logs, levantar servicios, entender backend y desenvolverse en CI/CD; automatización con Cypress (entender, ejecutar, mantener y ampliar una suite existente). Requisitos: 2+ años de experiencia en QA, functional/regression testing sólido, API testing con Postman, comodidad con Terminal, Linux/Unix, Git, test automation (idealmente Cypress), leer/depurar código y automatizaciones sencillas; Ruby, JavaScript/TypeScript o Python suman; inglés avanzado/bilingüe para trabajar con equipos en USA. Condiciones: 100% remoto desde México (preferencia Apodaca/Monterrey pero no excluyente), contratación directa, tiempo indeterminado, horario ~8:30-16:30 Mountain Time, 21 días de aguinaldo, vales de despensa, fondo de ahorro y seguros médicos. Postulación por DM con CV en inglés.',
    tags: ['qa', 'manual testing', 'functional testing', 'regression', 'api testing', 'postman', 'cypress', 'git', 'linux', 'unix', 'ci/cd', 'automation', 'test automation', 'javascript', 'python', 'ruby'],
    salary: '',
    date: '2026-09-08',
  },

  // ============ PERÚ ============
  {
    id: 'curated-pe-valtx-qa-ia',
    source: 'Directo (Valtx)',
    title: 'QA Automatizador – IA',
    company: 'Valtx',
    location: 'Lima, Perú',
    regionGuess: 'peru',
    applyUrl: 'https://www.valtx.pe',
    description:
      'Valtx busca QA Automatizador – IA. Misión: diseñar e implementar una solución de QA potenciada por IA con agentes capaces de generar escenarios BDD, casos de prueba y scripts de automatización, integrándose con Jira/Rovo y usando Python, GitHub Copilot y modelos Claude. Tecnologías clave: Python, GitHub Copilot, modelos Claude, Jira/Rovo, BDD y automatización de pruebas, IA aplicada a QA. Postulación: enviar CV a lnunural@valtx.pe con nombre de posición y expectativas salariales.',
    tags: ['qa automation', 'automation', 'python', 'bdd', 'gherkin', 'jira', 'ai', 'ia'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-pe-qds-qa-auto',
    source: 'Directo (QDS)',
    title: 'QA Automatizador',
    company: 'QDS - Quality & Development Software SAC',
    location: 'Lima, Perú (Híbrido)',
    regionGuess: 'peru',
    applyUrl: 'https://www.qds.com.pe',
    description:
      'QDS busca QA Automatizador (solo Perú, híbrido). Requisitos: Postman, Playwright y TypeScript, 3 años de experiencia en la posición, gestión de defectos (Jira/Azure DevOps), diseño de casos de prueba (Gherkin/BDD), pruebas funcionales, no funcionales y de regresión. Deseable: Performance Testing (JMeter) y conocimientos de OWASP. Enviar CV a eliana.santini@qds.com.pe.',
    tags: ['qa automation', 'automation', 'playwright', 'typescript', 'postman', 'api testing', 'bdd', 'gherkin', 'jira', 'azure devops', 'regression'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-pe-interseguro-tpo',
    source: 'Directo (Interseguro)',
    title: 'Technical Product Owner',
    company: 'Interseguro Compañía de Seguros',
    location: 'Lima, Perú (Híbrido)',
    regionGuess: 'peru',
    applyUrl: 'https://l1nq.com/kb5gxw6',
    description:
      'Interseguro busca Technical Product Owner (solo Perú, híbrido). Bachiller o titulado en Ingeniería de Sistemas/Informática/Software. 3 a 5 años liderando equipos de desarrollo. Tecnologías: Angular, React, Vue, Nuxt, Java, .NET, Python, Golang, Node.js y SQL Server. Inglés intermedio deseable. Conocimientos de modelamiento de datos, virtualización y despliegue en Cloud, herramientas de IA Generativa (Cursor), Google Cloud Platform (Cloud Run, Cloud Storage, Cloud SQL, Cloud Functions, Pub/Sub), Kubernetes y CI/CD. Postular en el link.',
    tags: ['cloud', 'sql', 'python', 'agile', 'kubernetes', 'ci/cd', 'ai'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-pe-coderslab-qa-ssr',
    source: 'Directo (CodersLab)',
    title: 'Especialista QA SSR',
    company: 'CodersLab',
    location: 'Lima, Perú (Híbrido)',
    regionGuess: 'peru',
    applyUrl: 'https://www.coderslab.io',
    description:
      'CodersLab busca Especialista QA SSR (Lima, Perú, híbrido). Mínimo 3 años ejecutando pruebas manuales de QA (excluyente). Certificación ISTQB Foundation Level o afines (excluyente). Consultas en bases de datos. Conocimientos o nociones de automatización. Ejecución y pruebas de servicios/APIs (Postman o similares). Ejecución de procesos ETL. Experiencia en sector bancario. Enviar CV a veronica.rueda@coderslab.io.',
    tags: ['qa', 'manual testing', 'testing', 'sql', 'api testing', 'postman', 'banking', 'istqb', 'etl'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-pe-novacomp-sr-sdet',
    source: 'Directo (Novacomp)',
    title: 'Senior QA Automation / SDET',
    company: 'Novacomp',
    location: 'Lima, Perú (Híbrido)',
    regionGuess: 'peru',
    applyUrl: 'https://www.novacomp.com',
    description:
      'Novacomp busca Senior QA Automation / SDET (Lima, Perú, híbrido). Automatización enfocada en APIs (60-70%), Web (30%) y Mobile. Dominio de Playwright con TypeScript y herramientas como Karate o Selenium. Pruebas de rendimiento con K6. Enviar CV a fflores@crnova.com.',
    tags: ['qa automation', 'sdet', 'automation', 'api testing', 'playwright', 'typescript', 'selenium', 'mobile testing', 'performance testing'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-pe-indra-qa-manager-uat',
    source: 'Directo (Indra)',
    title: 'QA Manager (UAT Banca)',
    company: 'Indra',
    location: 'San Isidro, Lima, Perú',
    regionGuess: 'peru',
    applyUrl: 'https://wa.link/ea14nb',
    description:
      'Indra busca QA Manager para liderar la estrategia y gestión de pruebas UAT en proyectos de alta criticidad del sector bancario. Requisitos: 8+ años en QA y 3+ años liderando equipos/servicios de pruebas; experiencia en QA/UAT, gestión de riesgos, integraciones, migraciones y Go/No-Go; experiencia indispensable en sector bancario; Jira/Xray o equivalentes; Ingeniería de Sistemas/Informática/Industrial. Deseable: ISTQB, PMP/PMI, Scrum/Agile y Bantotal. Presencial en San Isidro, Lima, lunes a viernes 9-18hs. Postulación: gmcaballerop@indracompany.com.',
    tags: ['qa', 'qa manager', 'uat', 'testing', 'banking', 'banca', 'jira', 'xray', 'agile', 'scrum', 'test cases'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-pe-nttd-bootcamp-qa',
    source: 'Directo (NTT DATA)',
    title: 'Bootcamp QA Automatizador',
    company: 'NTT DATA Europe & Latam',
    location: 'Perú (100% Remoto, provincias)',
    regionGuess: 'peru',
    applyUrl: 'https://lnkd.in/eZcd2R5T',
    description:
      'NTT DATA Europe & Latam busca profesionales para su Bootcamp QA Automation, convocatoria para profesionales que residan en provincias del Perú, modalidad 100% remota. Requisitos: 1 a 2 años de experiencia en QA Manual, experiencia en pruebas funcionales y reporte de incidencias, manejo de Jira y/o Postman (deseable), interés en desarrollarse en Automatización de Pruebas. Enviar CV a gbonillr@nttdata.com o postular en el anuncio.',
    tags: ['qa automation', 'qa', 'automation', 'manual testing', 'functional testing', 'jira', 'postman', 'api testing', 'test automation'],
    salary: '',
    date: '2026-09-01',
  },

  // ============ COLOMBIA ============
  {
    id: 'curated-co-ezertech-analista-qa',
    source: 'Directo (EZERTECH)',
    title: 'Analista QA',
    company: 'EZERTECH',
    location: 'Barranquilla, Colombia',
    regionGuess: 'colombia',
    applyUrl: 'https://www.ezertech.com.co',
    description:
      'EZERTECH busca Analista QA para software empresarial del sector salud (EPS). Mínimo 3 años en pruebas de software empresarial. Responsabilidades: diseñar planes, escenarios y casos de prueba; ejecutar pruebas funcionales, de integración y regresión; validaciones de datos; pruebas y validación de APIs; documentar y dar seguimiento a defectos; emitir concepto de calidad del release. Deseable: experiencia en sector salud/EPS/IPS/aseguramiento/facturación en salud, Postman para APIs, SQL básico para validación de datos, metodologías ágiles/Scrum, Jira, Azure DevOps o GitLab. Presencial en Barranquilla. Postulación por mail a soporte@ezertech.com.co.',
    tags: ['qa', 'analista qa', 'functional testing', 'manual testing', 'api testing', 'postman', 'sql', 'agile', 'scrum', 'jira', 'azure devops'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-co-htqa-fabrica-pruebas',
    source: 'Directo (HTQA)',
    title: 'QA Engineer – Fábrica de Pruebas (Java/Python, Spark, Ab Initio, PL/SQL)',
    company: 'HTQA – Human Team Technology QA',
    location: 'Bogotá, Colombia',
    regionGuess: 'colombia',
    applyUrl: 'https://www.htqasas.com',
    description:
      'HTQA (Human Team Technology QA, Bogotá) busca profesionales QA con experiencia real y comprobable en tecnologías específicas: Java + Python, Apache Spark, Ab Initio y PL/SQL, según cada vacante. No buscan un QA generalista: piden coincidencia del 100% con la tecnología solicitada de su Fábrica de Pruebas. Enviar CV a rrhh@htqasas.com o kdelgado@htqasas.com.',
    tags: ['qa', 'java', 'python', 'apache spark', 'ab initio', 'pl/sql', 'big data', 'testing', 'data', 'etl'],
    salary: '',
    date: '2026-09-08',
  },
  {
    id: 'curated-co-capgemini-qa-spark-plsql',
    source: 'Capgemini (LinkedIn)',
    title: 'QA Funcional Spark PL/SQL Sr',
    company: 'Capgemini',
    location: 'Colombia (100% Remoto)',
    regionGuess: 'colombia',
    applyUrl: 'https://www.capgemini.com/co-es/',
    description:
      'Capgemini busca QA Funcional Spark PL/SQL Sr, modalidad 100% remoto, contrato a término fijo por 3 meses. Requisitos: 4+ años de experiencia en pruebas de software, pruebas funcionales, Spark, PL/SQL, servicios REST y SOAP, JMeter, SoapUI, Postman y Appium. Postulación a través de la publicación o compartiendo la oportunidad.',
    tags: ['qa', 'functional testing', 'spark', 'pl/sql', 'rest', 'soap', 'jmeter', 'soapui', 'postman', 'appium', 'manual testing'],
    salary: '',
    date: '2026-09-08',
  },
  {
    id: 'curated-co-qa-sr-js-webdriverio',
    source: 'Reclutador (LinkedIn)',
    title: 'Sr. QA Automation Engineer (JavaScript)',
    company: 'Confidencial (AR/CO/MX/BR)',
    location: 'Colombia (100% Remoto)',
    regionGuess: 'colombia',
    applyUrl: '',
    description:
      'Sr. QA Automation Engineer (JavaScript) para un proyecto global en crecimiento, 100% remoto (AR/CO/MX/BR). Requisitos: +5 años en Quality Testing, +3 años en QA Automation, pipelines CI/CD (CircleCI preferido), automatización frontend con JavaScript + WebdriverIO, automatización backend, diseño orientado a objetos y bases de datos relacionales y no relacionales. Qué vas a hacer: liderar la calidad end-to-end, diseñar y mantener suites de automatización frontend/backend, coordinar releases completos (go/no-go, sanity checks post-deploy), visibilidad de cobertura/riesgos, proponer mejoras y roadmap de calidad. Postulación por MD (publicación #QA #Automation #SDET #JavaScript #WebdriverIO).',
    tags: ['qa automation', 'automation', 'sdet', 'javascript', 'webdriverio', 'ci/cd', 'circleci', 'frontend testing', 'api testing', 'backend testing', 'release management'],
    salary: '',
    date: '2026-09-08',
  },
  {
    id: 'curated-co-qa-auto-ai-llm',
    source: 'Reclutador (LinkedIn)',
    title: 'QA Automation Engineer (AI / LLM)',
    company: 'Confidencial (Colombia)',
    location: 'Colombia',
    regionGuess: 'colombia',
    applyUrl: '',
    description:
      'QA Automation Engineer para nuevo proyecto, contratación por nómina en Colombia, proyecto de 6 meses, inglés básico. Buscan +3 años en QA/automatización, experiencia en pruebas de soluciones de AI, GenAI, LLMs o agentes de AI, Azure DevOps y CI/CD, evaluación de LLMs (hallucination, groundedness y calidad de respuestas), manejo de YAML/JSON. Postulación: contactar al reclutador vía LinkedIn (publicación #QAAutomation #GenAI #LLM #Colombia).',
    tags: ['qa automation', 'automation', 'ai', 'ia', 'llm', 'generative ai', 'azure devops', 'ci/cd', 'api testing'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-co-hyg-analista-qa',
    source: 'Directo (HyG Consultores)',
    title: 'Analista de Requisitos y Calidad de Software (QA)',
    company: 'HyG Consultores',
    location: 'Medellín, Colombia',
    regionGuess: 'colombia',
    applyUrl: 'https://www.hyg.com.co',
    description:
      'HyG Consultores busca Analista de Requisitos y Calidad de Software (QA) con mínimo 1 año de experiencia, presencial en Medellín / Valle de Aburrá. Requisitos clave: metodologías ágiles, levantamiento de requisitos, diseño/ejecución de pruebas, Jira/Azure DevOps, SQL y Excel. Enviar hoja de vida a gestionhumana@hyg.com.co.',
    tags: ['qa', 'analista funcional', 'analista', 'testing', 'functional testing', 'test cases', 'jira', 'azure devops', 'sql', 'agile'],
    salary: '',
    date: '2026-09-01',
  },

  // ============ CHILE ============
  {
    id: 'curated-cl-randstad-qa-junior',
    source: 'Directo (Randstad Chile)',
    title: 'Analista QA Junior',
    company: 'Randstad',
    location: 'Santiago, Chile (Híbrido)',
    regionGuess: 'chile',
    applyUrl: 'https://www.randstad.cl',
    description:
      'Randstad Chile busca Analista QA Junior para empresa de soluciones tecnológicas de gestión humana. Modalidad híbrida en Las Condes (Santiago de Chile), contrato plazo fijo luego indefinido. Requisitos: titulado/a de Ingeniería en Informática o afines (0 a 1 año de experiencia), manejo de JavaScript, Python, SCRUM y RESTful, conocimientos en buenas prácticas de QA, diseño y automatización de pruebas. Enviar CV a mariana.herrera@randstad.cl con asunto "QA Analyst Junior".',
    tags: ['qa', 'analista qa', 'qa automation', 'testing', 'javascript', 'python', 'scrum', 'rest', 'test automation'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-cl-socius-qa-auto',
    source: 'Directo (SOCIUS)',
    title: 'QA Automatizador Semi Senior',
    company: 'SOCIUS',
    location: 'Santiago, Chile (Híbrido)',
    regionGuess: 'chile',
    applyUrl: 'https://lnkd.in/d2yVy8qU',
    description:
      'SOCIUS busca QA Automatizador Semi Senior (híbrido, Santiago de Chile), proyecto largo plazo, 3 vacantes. Qué harás: diseñar, desarrollar y mantener pruebas automatizadas; ejecutar pruebas funcionales, de APIs y performance; integrar pruebas en pipelines CI/CD; analizar resultados, documentar incidencias y hacer seguimiento de defectos. Qué buscan: automatización con Selenium, Cucumber y/o Karate, pruebas de APIs con Postman, SQL para validación de datos, GitHub y/o Jenkins, performance con JMeter y/o BlazeMeter, metodologías ágiles. Plus: BrowserStack, Azure, CyberArk o IntelliJ, certificación ISTQB y uso de IA (Copilot, PraIA). Aplicar en el link.',
    tags: ['qa automation', 'automation', 'selenium', 'cucumber', 'karate', 'api testing', 'postman', 'sql', 'github', 'jenkins', 'jmeter', 'blazemeter', 'performance testing', 'agile', 'browserstack', 'istqb', 'ai'],
    salary: '',
    date: '2026-09-08',
  },
];
